name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ayushgautamcodes
          outputs: |
            dist/github-snake.svg?palette=github
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#58A6FF

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add dist/
          git diff --cached --quiet || git commit -m "Update contribution snake"

          git push
